apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a-deployment
  labels:
    app: service-a
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a

    spec:
      containers:
        - name: service-a
          image: mumcourses/service-a:latest
          ports:
            - containerPort: 8080
          env:
            - name: KEY1
              valueFrom:
                configMapKeyRef:
                  name: service-a-config
                  key: someKey1
            - name: NEXT_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: service-a-config
                  key: nextService
            - name: SERVICE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: service-a-secrets
                  key: service-api-key
            #MYSQL
            - name: MYSQL_HOST
              value: service-a-db

            - name: MYSQL_USER
              value: root

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: service-a-secrets
                  key: mysql-root-password